name = "corss"
compatibility_date = "2024-07-27"

[build]
command = "npx wrangler deploy"

[site]
bucket = "./public"

[[routes]]
pattern = "/*"
zone_name = "yourdomain.com"  # Optional for custom domain
